### ISSUE TITLE
ConvNorm for 1D Kernels

### ISSUE THREAD

**Issue by okbalefthanded** [shengliu66/ConvNorm#4]
Hi,
Thanks for providing the complete code for the ConvNorm paper, my question is about replacing the Conv2d operations with ConvNorm using 1d kernel size eg. (1, 16). 
For a kernel length smaller than the input, the V tensor will have smaller dimension which will raise an error in the multiplication (V*cout). After checking the code I think the error is due to the absence of zero padding for the kernel as in the case of 2D kernels.

**Comment by Heimine** [comment]
Hi,
Thanks for your attention to our work.
I'm not entirely sure I understand your question, what do you mean by replacing Conv2d with a 1d kernel size? Could you give an example perhaps?

Thanks!

**Comment by okbalefthanded** [comment]
Hi,

In applications like Speech Recognition, Time Series Data and EEG, we often use 1D kernel size, instead of the classical 3x3 for image classification we use something like 1x125 for both a 2D matrix or 1D vector of data. Using the actual ConvNorm code, a kernel with the same length of the input works fine, otherwise an error occurs. The following colab notebook demonstrates the issue:
https://colab.research.google.com/drive/1NjhGtfZPrDsE7nnXD1u-AraoAE8mTlEy?usp=sharing

PS: the  Convorm class used in the notebook is a well tested update to support Pytorch versions >= 1.8, in which the fft module has been modified.

**Comment by Heimine** [comment]
Thank you very much for the detailed sample of the problem. Now I understand it. 
Since we mainly explored our method on 2D CV tasks, so deal with 1D kernel, especially even-sized 1D kernel is new to us, which is the reason we didn't consider this case during writing the code. But since the idea could be extended in this scenario, I have made some edits to your [colab notebook](https://colab.research.google.com/drive/1011QduZjfxCU66UZrJph097fsvxv-Thy?usp=sharing) to make it work. The primary changes are all related to padding, which is quite different for distinct scenarios. We have talked about this in detail in our [paper](https://arxiv.org/pdf/2103.00673.pdf) in Appendix B.2 and B.3, so please refer there for a more detailed view of our method. 

Besides, I'm not entirely sure in your use case, whether you care about input size = output size, I tried to make this exact in the notebook but you are welcome to change this behavior if this isn't something important.
Let me know if the edits help to solve your problem. Thanks!

**Comment by okbalefthanded** [comment]
Thanks for the edits, at first execution the code runs correctly, I'll let you know about the results once the experiments will be done.
My use case is rather arbitrary, the kernel sizes vary for each layer.
